word = input("Please enter a word: ")
print(f'First character: {word[0]}')
print(f'Last character: {word[-1]}')
print(f'First four characters: {word[0:4]}')
print(f'Every other character: {word[4:]}')
print(f'Backward: {word[::-1]}')