dist = round(float(input("Please enter the trip distance (in miles): ")),1)
avg_spd = round(float(input("Please enter the average speed (in m/h): ")),1)
fuel_eff = round(float(input("Please enter the fuel efficiency (in m/g): ")),1)
gas_price = round(float(input("Please enter the gas price per gallon (in $): ")),1)
print()
print(f'For a trip of {dist} miles at an average speed of {avg_spd} mph, the driving time will be {round((avg_spd ** (-1)) * dist, 1)} hours.')
print()
print(f'Your car will use {round((fuel_eff ** (-1)) * dist,1)} gallons of gas, and the total fuel cost will be ${round(gas_price * ((fuel_eff ** (-1)) * dist),2)}.')